apiVersion: v1
kind: Pod
metadata: 
  name: multi-container-pod
spec:
  containers:                                  #you can add the mulitple containers here.
    - name: nginx-container
      image: nginx
    - name: busybox-container
      image: busybox
      command: ["sleep", "60"]  #this is the command tells the system to pause or sleep the container

