apiVersion: v1
kind: Pod
metadata:
  name: redis-pod                 
spec:
  containers:                     
    - name: redis                  # you can use any name 
      image: redis                 # change the name of image which you want.

